# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ContinuousIntegration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # install deps
      - run: npm ci
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # JS
      - run: npm run eslint
      # CSS
      - run: npm run stylelint
      # HTML
      - run: npm run htmlhint
      # Markdown
      - run: npm run markdownlint
      # Formatting
      - run: npm run prettier
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
  build:
    needs: [setup, lint, test]
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
