# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ContinuousIntegration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # install deps
      - run: npm ci
      # lint JS
      - run: npm run eslint
      # lint CSS
      - run: npm run stylelint
      # lint HTML
      - run: npm run htmlhint
      # lint Markdown
      - run: npm run markdownlint
      # Formatting
      - run: npm run prettier
      # run tests
      - run: npm run test
      # try build
      - run: npm run build
